version: '3.7'

services:
  project-postgres:
    image: postgres:12
    container_name: project-postgres
    hostname: project-postgres
    stop_signal: SIGTERM
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      # - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      # - ./config/initdb.d:/docker-entrypoint-initdb.d
      # - /containers/certbot/keys:/keys:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # networks:
    #   - database
    #   - default
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready || exit 1"]
      interval: 180s
      start_period: 10s
      timeout: 15s
      retries: 5
    command:
      - "postgres"
      # - "-c"
      # - "config_file=/etc/postgresql/postgresql.conf"

volumes:
 db:

# networks:
#   web:
#     external:
#       name: webproxy
#   database:
#     external:
#       name: database
#   internal: