type Profile {
  id: ID!
  User: User!
  diplayName: String!
  createdAt: Date!
  updatedAt: Date!
}

type User {
  id: ID!
  token: String!
  name: String!
  createdAt: Date!
  updatedAt: Date!
  Profile: Profile!
  Groups: [UserGroup]
}
