type Mutation {
    login(userName: String, password: String): User
}

type Profile {
  id: ID!
  User: User!
  diplayName: String!
  createdAt: Date!
  updatedAt: Date!
}

type User {
  id: ID!
  token: String
  name: String!
  createdAt: Date!
  updatedAt: Date!
  Profile: Profile!
  Groups: [UserGroup]
}

type UserGroup {
  id: ID!
  Users: [User!]!
  displayName: String!
  extraData: String
  createdAt: Date!
  updatedAt: Date!
  deletedAt: Date!
}
